name: Release ModernFix Artifacts

on:
  release:
    types:
      - published

jobs:
  release:
    if: github.repository_owner == 'embeddedt'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true
      - name: Remove tags for release on other versions
        run: ./scripts/tagcleaner.sh
      - name: Build and publish mod to CurseForge & Modrinth
        run: ./gradlew publishToModSites copyJarToBin
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Upload assets to GitHub
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'bin/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add changelog to release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          replacebody: true
          files: "CHANGELOG.md"
