name: Update wiki using WikiGen

on:
  push:
    branches:
      - '1.**'

jobs:
  wikigen:
    if: github.repository_owner == 'embeddedt'
    runs-on: ubuntu-latest
    concurrency:
      group: wiki-generation
      cancel-in-progress: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate Markdown Patch-List
        run: python3 scripts/gen-markdown-patchlist.py
      - name: Upload generated file to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "doc/generated"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.WIKI_TOKEN }}